### ISSUE TITLE
It's ashamed that you add torvalds into every your repo

### ISSUE THREAD

**Issue by cgcgbcbc** [xxg1413/leetcode#44]
Which will bother more than 35.7k people.

**Comment by xxg1413** [comment]
你好，我是看到别人在这样做，实验一下，只加了一两个项目。现在我的账号被封，不知道是不是这个原因。

谢谢你的提醒。

我timeline截图：
![image](https://cloud.githubusercontent.com/assets/1381803/14011990/bc5bc1f6-f1dd-11e5-8503-e1560a43736c.png)

Github官方认为我是机器人：
![image](https://cloud.githubusercontent.com/assets/1381803/14012033/fb5f6aba-f1dd-11e5-9b97-96da7bd354e6.png)
